### ISSUE TITLE
Question about pypi/matplotlib-inline pointing to a fork of this project.

### ISSUE THREAD

**Issue by crisbal** [ipython/matplotlib-inline#6]
Hello,

I was taking a look at https://pypi.org/project/matplotlib-inline/ .

Is there any reason why as a source/homepage it points to a fork of @martinRenou instead of this repo? Isn't this the "official" repo? As of my understanding, Martin currently works for your organization so it is possible there was a mistake when publishing to Pypi?

To me it feels strange to have the official package source to be here (ipython/matplotlib-inline) but deployed/owned by Martin on Pypi (via martinRenou/matplotlib-inline, which clearly is shown by GitHub as a fork) . 

Thanks for the clarification, 

Cristian

**Comment by martinRenou** [comment]
Hello,

Thanks for reporting. This is indeed unintended, the matplotlib-inline repo started under my account and was moved there. There was a fix of the url https://github.com/ipython/matplotlib-inline/pull/3 but this was never released and published to PyPi.

We should fix that.

**Comment by martinRenou** [comment]
This should be fixed now. Thanks :)

**Comment by crisbal** [comment]
Perfect! Thanks for the quick turnaround
